### ISSUE TITLE
TypeError: dto.toEntity is not a function

### ISSUE THREAD

**Issue by fernandodeabreupereira** [GauSim/nestjs-typeorm#1]
Hello, first I would like to thank you for the beautiful example presented by you.

I'm trying to replicate your code, following the article posting on Medium (https://medium.com/@gausmann.simon/nestjs-typeorm-and-postgresql-full-example-development-and-project-setup-working- with-database-c1a2b1b11b8f). I reached the end, but when I POST to / item, I get the following message:

![image](https://user-images.githubusercontent.com/15267646/72649856-838cb580-395d-11ea-90a9-39d63d1316e8.png)

Can you help me? Thank you!

**Comment by fcastell** [comment]
Hello, thank you for your excellent article :)

I have the same problem and this is my solution :

Inside item.dto.ts make the method toEntity static :

`public static toEntity(dto: ItemDTO, user: User = null) {
...
}`

and inside item.service.ts :

`
return this.repo.create(ItemDTO.toEntity(dto, user))
`

best reguards

**Comment by GauSim** [comment]
Thanks for pointing that out.
fixed the demo code 
[4a9bc8c969915898bbc888a4348129a4a0486a8f](https://github.com/GauSim/nestjs-typeorm/commit/4a9bc8c969915898bbc888a4348129a4a0486a8f)
